version: '3.8'
services:
  bot:
    build: .
    container_name: touch-grass-bot
    env_file: .env
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:latest
    container_name: touch-grass-bot-db
    env_file: .env
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped