name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build